"""Reads openapi.json and writes namespaces_gen.go.

Same naming rule as the Python and TypeScript SDKs: the operationId is split on `_` into
namespace and method parts, `-` separates words inside a part, a single-part operationId
gets `Compute`. So `vedic_dashas_vimshottari_maha` becomes aw.Vedic.DashasVimshottariMaha.

Skipped: path templates (`/webhooks/{id}/test`), non-JSON answers (embeds, SSE streams) and
the `/public/*` mirrors. Every skipped path is still reachable through Client.Do.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "openapi.json"
OUT = ROOT / "namespaces_gen.go"


def words(s: str) -> list[str]:
    return [w for w in (re.sub(r"[^a-zA-Z0-9]", "", p) for p in re.split(r"[-]+", s)) if w]


def camel(parts: list[str]) -> str:
    out = "".join(w[:1].upper() + w[1:].lower() for p in parts for w in words(p))
    return "N" + out if out[:1].isdigit() else out


def ascii_doc(s: str) -> str:
    table = {0x00D7: "x", 0x2014: "-", 0x2013: "-", 0x2018: "'", 0x2019: "'", 0x201C: '"', 0x201D: '"'}
    return s.translate(table).replace("\n", " ").strip()


def collect(spec: dict) -> dict[str, list[dict]]:
    by_ns: dict[str, list[dict]] = {}
    for path, methods in spec.get("paths", {}).items():
        op = methods.get("post") or methods.get("get")
        verb = "POST" if methods.get("post") else "GET"
        if not op or not op.get("operationId") or "{" in path or path.startswith("/public/"):
            continue
        ok = ((op.get("responses") or {}).get("200") or {}).get("content") or {}
        if "application/json" not in ok:
            continue
        parts = [p for p in (re.sub(r"[{}]", "", x) for x in op["operationId"].split("_")) if p]
        if not parts:
            continue
        ns = camel([parts[0]])
        method = "Compute" if len(parts) == 1 else camel(parts[1:])
        if not ns or not method:
            continue
        by_ns.setdefault(ns, []).append({"method": method, "path": path, "verb": verb, "summary": op.get("summary") or ""})
    return by_ns


def main() -> int:
    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    by_ns = collect(spec)
    bad = 0
    for ns, items in by_ns.items():
        seen: dict[str, str] = {}
        for it in items:
            if seen.get(it["method"], it["path"]) != it["path"]:
                print(f"collision: {ns}.{it['method']} -> {seen[it['method']]} vs {it['path']}", file=sys.stderr)
                bad += 1
            seen[it["method"]] = it["path"]
    if bad:
        return 1

    out = [
        "// Code generated by scripts/generate.py from openapi.json. DO NOT EDIT.",
        f"// API version {spec['info']['version']}.",
        "",
        "package astroway",
        "",
        'import "context"',
        "",
        "type namespaces struct {",
    ]
    for ns in sorted(by_ns):
        out.append(f"\t{ns} *{ns}Service")
    out += ["}", "", "func (n *namespaces) init(c *Client) {"]
    for ns in sorted(by_ns):
        out.append(f"\tn.{ns} = &{ns}Service{{c}}")
    out += ["}", ""]
    for ns in sorted(by_ns):
        out += [f"// {ns}Service groups the {ns} endpoints.", f"type {ns}Service struct{{ c *Client }}", ""]
        for it in sorted(by_ns[ns], key=lambda x: x["method"]):
            doc = ascii_doc(it["summary"]) or it["path"]
            out.append(f"// {it['method']}: {doc} ({it['verb']} {it['path']}).")
            if it["verb"] == "GET":
                out.append(f"func (s *{ns}Service) {it['method']}(ctx context.Context, opts ...RequestOption) (*Response, error) {{")
                out.append(f'\treturn s.c.Do(ctx, "GET", "{it["path"]}", nil, opts...)')
            else:
                out.append(f"func (s *{ns}Service) {it['method']}(ctx context.Context, body any, opts ...RequestOption) (*Response, error) {{")
                out.append(f'\treturn s.c.Do(ctx, "POST", "{it["path"]}", body, opts...)')
            out += ["}", ""]
    OUT.write_text("\n".join(out), encoding="utf-8")
    n = sum(len(v) for v in by_ns.values())
    print(f"{len(by_ns)} namespaces, {n} methods -> {OUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
